### ISSUE TITLE
Tagesziel Quizrunde

### ISSUE THREAD

**Issue by cnowagk** [th-koeln/wba1-2016-datagram#11]
Wiki-Seite erstellen
Styleguide für das Gerüst und die Schriften etc. anschauen
(Mit CSS anfangen)

**Comment by lwirtz1** [comment]
Farben:
gelb:#E9C20C
hell grau:#F8F5E4
grau:#929292
rot#CB0727

Nummerierung: Oswald regular 22px
Button: Height: 50px / Noto Sans Regular / 16px
![image](https://cloud.githubusercontent.com/assets/22662727/19351738/2fab5f76-915d-11e6-9887-33c99824cf6b.png)
