### ISSUE TITLE
JSONs für 4 Quizze (Vorläufig)

### ISSUE THREAD

**Issue by vkryutso** [th-koeln/wba1-2016-datagram#110]
## 1. Quiz

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Wie heißt ein langjahriges Maskottchen des SV Werder Bremen?",

  "a1": "Pico(Heidschnuckenbock)",
  "a2": "Werner Bremen(Esel)",
  "a3": "Roland(Fischreiher)",
  "a4": "Konig Otto(Comic-Figur)",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Werders Rekordtorschutze Claudio Pizarro ist ein absoluter Pferde-Narr. Mit seinem fruheren Bayern-Mitspieler Thomas Muller hat er ein gemeinsames Pferd. Wie hei?t es?",

  "a1": "Mia san Triple",
  "a2": "Don Jupp",
  "a3": "Hoene?",
  "a4": "Hattrick",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Wann wurde der Verein - damals noch FV Werder Bremen - gegrundet?",

  "a1": "04. Februar 1899",
  "a2": "01. Oktober 1893",
  "a3": "07. Juli 1907",
  "a4": "01. Januar 1920",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Wie lauten die Vornamen der drei Bundesliga-Rekordspieler des SV Werder Bremen?",

  "a1": "Dieter, Horst-Dieter, Dieter",
  "a2": "Torsten, Dieter, Dieter",
  "a3": "Dieter, Wynton, Dieter",
  "a4": "Dieter, Horst-Dieter, Horst",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Arnd Zeigler ist einer der gro?ten Fu?ball-Nerds der Republik, regiert "Zeiglers wunderbare Welt des Fu?ball" im Radio und Fernsehen und ist au?erdem Stadionsprecher im Weserstadion. Wie aber hei?t sein Co-Stadionsprecher?",

  "a1": "Christian "Stolli" Stoll",
  "a2": "Manfred "Wolle" Wollenhaupt",
  "a3": "Andreas "Action-Andy" Schneider",
  "a4": "Norbert "Nobbi" Germeshausen",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Wann wurde Werder Bremen zum ersten Mal Deutscher Meister?",

  "a1": "1965",
  "a2": "1931",
  "a3": "1988",
  "a4": "2004",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "2013 wurde Werder Bremen Deutscher Meister. In welcher Sportart?",

  "a1": "Tischtennis",
  "a2": "Handball",
  "a3": "Basketball",
  "a4": "Feldhockey",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Welches dieser Zitate wird nicht Werders „Ostfriesen-Alemao“ Dieter Eilts zugeschrieben?",

  "a1": "„Wir durfen jetzt nicht den Sand in den Kopf stecken.“",
  "a2": "„Das interessiert mich wie eine geplatzte Currywurst im ostfriesischen Wattenmeer.“",
  "a3": "„Wenn meine Oma ein Bus ware, dann konnte sie hupen.“",
  "a4": "„Moin moin, Gascoigne.“",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Claudio Pizarro hat in dieser Saison Marvo Bode als Werders Bundesliga-Rekordtorschutze abgelost. Gegen wen und wie erzielte er sein erstes Bundesliga-Tor?",

  "a1": "1. FC Kaiserslautern, Kopfball",
  "a2": "Borussia Monchengladbach, Fallruckzieher",
  "a3": "Alemannia Aachen, Elfmeter",
  "a4": "1. FC Koln, Hackentrick",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Werder Bremen Quiz",
  "text": "Auf welchem Platz rangiert Werder Bremen in der ewigen Tabelle der Bundesliga?",

  "a1": "2. Platz",
  "a2": "5. Platz",
  "a3": "16. Platz",
  "a4": "9. Platz",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

## 2. Quiz

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Wie hoch ist der Marktwert des aktuellen FC Bayern Kaders (Stand Saison 16/17)?",

  "a1": "ca. 580 Millionen",
  "a2": "ca. 590 Millionen",
  "a3": "ca. 540 Millionen",
  "a4": "ca. 600 Millionen",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Der FC Bayern gab in der Saison 1994/95 seine Champions-League-Premiere. Wie weit kamen sie?",

  "a1": "Halbfinale",
  "a2": "Finale",
  "a3": "Viertelfinale",
  "a4": "Achtelfinale",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Zwei Mal gewann der FC Bayern Munchen den Weltpokal, 1976 und 2001. Wer erzielte 2001 das Siegtor?",

  "a1": "Sami Kuffour",
  "a2": "Stefan Effenberg",
  "a3": "Bixente Lizarazu",
  "a4": "Mehmet Scholl",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "In welcher Saison erreichte der FC Bayern die schlechteste Bundesligaendplatzierung der Vereinsgeschichte?",

  "a1": "1977/78",
  "a2": "1994/95",
  "a3": "1991/92",
  "a4": "1976/77",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Wer erzielte in der Triple-Saison 2012/13 die meisten Tore fur den FC Bayern in der Bundesliga?",

  "a1": "Mario Mandzukic",
  "a2": "Thomas Muller",
  "a3": "Mario Gomez",
  "a4": "Franck Ribery",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Gegen welche Mannschaft fuhr der FC Bayern den hochsten Sieg (8:0) der letzten 10 Jahre ein?",

  "a1": "Hamburger SV",
  "a2": "VfB Stuttgart",
  "a3": "Werder Bremen",
  "a4": "Bayer Leverkusen",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Welche Vereine gewannen, neben dem FC Bayern Munchen, alle europaischen Pokalwettbewerbe?",

  "a1": "FC Chelsea, Juventus Turin und Ajax Amsterdam",
  "a2": "Ajax Amsterdam, Inter Mailand, FC Barcelona",
  "a3": "Juventus Turin, Borussia Dortmund, Real Madrid",
  "a4": "Inter Mailand, Manchester United, FC Barcelona",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Der FC Bayern wurde am 27. Februar 1900 in einem Restaurant gegrundet. Was war der Name des Restaurants?",

  "a1": "Gisela",
  "a2": "Hedwig",
  "a3": "Adelheid",
  "a4": "Rosmarie",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "In seiner Karriere als FC Bayern Trainer fiel Giovanni Trapattoni besonders durch seine – meist grammatikalisch falschen – Spruche auf. Welcher der folgenden Zitate ist nicht auf ihn zuruckzufuhren?",

  "a1": "„Ball rund muss in Tor eckig.“",
  "a2": "„Ich habe fertig!“",
  "a3": "„Was erlauben Strunz?“",
  "a4": "„...ware‘ schwach wie eine Flasche leer.“",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "FC Bayern Munchen Quiz",
  "text": "Wann gewann der FC Bayern Munchen das erste Mal die Fu?ballbundesliga?",

  "a1": "1969",
  "a2": "1976",
  "a3": "1966",
  "a4": "1971",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

## 3. Quiz

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Wer war der erste Trikotsponsor des BVB?",

  "a1": "Stadt Dortmund",
  "a2": "Wiesenhof",
  "a3": "Telekom",
  "a4": "Audi",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Was waren die ursprunglichen Vereinsfarben des BVB?",

  "a1": "wei?-blau",
  "a2": "schon immer schwarz-gelb",
  "a3": "rot-schwarz",
  "a4": "rot-wei?",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Das Heimstadion der Borussia ist der Signal Iduna Park. Wie viele Zuschauer passen in das Stadion?",

  "a1": "81.359 Platze",
  "a2": "75.000 Platze",
  "a3": "60.449 Platze",
  "a4": "69.250 Platze",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Borussia Dortmund operiert an der Borse. Wann erfolgte der erste Borsengang?",

  "a1": "31. Oktober 2000",
  "a2": "21. Dezember 2001",
  "a3": "27. Juni 1991",
  "a4": "01. Juli 2000",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Wie hoch ist der ungefahre Marktwert des aktuellen Borussia Dortmund Kaders (Stand Saison 16/17)?",

  "a1": "ca. 350 Millionen",
  "a2": "ca. 325 Millionen",
  "a3": "ca. 360 Millionen",
  "a4": "ca. 345 Millionen",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Wer war der erste Nationalspieler von Borussia Dortmund?",

  "a1": "August Lenz",
  "a2": "Erich Schanko",
  "a3": "Wolfgang Peters",
  "a4": "Alfred Schmidt",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Die Borussia unterhalt neben dem Fu?ball auch zwei weitere aktive Abteilungen. Welche sind dies?",

  "a1": "Handball, Tischtennis",
  "a2": "Leichtathletik, Tischtennis",
  "a3": "Handball, Boxen",
  "a4": "Eishockey, Handball",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Der BVB gewann insgesamt 8 Mal die Meisterschale. Was ist das Besondere an der Statistik?",

  "a1": "Sie gewannen den Meistertitel drei Mal zwei Saisons in Folge.",
  "a2": "Sie wurden immer einmal pro Jahrzehnt Meister.",
  "a3": "Sechs Titel davon gewannen sie innerhalb von zwanzig Jahren.",
  "a4": "Sie schafften drei Mal das Double.",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Wer war in der Double-Saison 2011/12 der Toptorjager der Borussia?",

  "a1": "Robert Lewandowski",
  "a2": "Shinji Kagawa",
  "a3": "Kevin Gro?kreutz",
  "a4": "Ivan Perisic",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "Borussia Dortmund Quiz",
  "text": "Der Rekordtorschutze erzielte in seiner Laufbahn 135 Bundesligatore fur den BVB. Wie hei?t er?",

  "a1": "Manfred Burgsmuller",
  "a2": "Robert Lewandowski",
  "a3": "Michael Zorc",
  "a4": "Pierre-Emerick Aubameyang",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

## 4. Quiz

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "Was ist das offizielle Grundungsdatum des VfB Stuttgart?",

  "a1": "09.09.1893",
  "a2": "01.01.1893",
  "a3": "24.12.1893",
  "a4": "11.11.1893",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "Der VfB Stuttgart zahlt zu den Grundungsmitgliedern der Bundesliga. Wie viele Grundungsmitglieder gab es insgesamt?",

  "a1": "16",
  "a2": "12",
  "a3": "18",
  "a4": "22",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "Welcher Spieler hat die meisten Ligaspiele fur den VfB absolviert?",

  "a1": "Robert Schlienz",
  "a2": "Guido Buchwald",
  "a3": "Cacau",
  "a4": "Zvonimir Soldo",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "2012 wahlten die VfB Fans zum 100-jahrigen Jubilaum der Fusion des FV Stuttgart mit dem Kronen-Club Cannstatt die „Jahrhundert-Elf“. Welcher dieser Spieler war nicht Teil dieser Elf?",

  "a1": "Cacau",
  "a2": "Sami Khedira",
  "a3": "Jurgen Klinsmann",
  "a4": "Krassimir Balakow",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "Das VfB-Trikot fallt besonders durch den markanten „Brustring“ auf. Seit wann ziert dieser schon das Trikot?",

  "a1": "1925",
  "a2": "1911",
  "a3": "1953",
  "a4": "1976",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "1989 stand der VfB Stuttgart im Finale des UEFA-Pokals. Gegen welche Mannschaft spielten sie?",

  "a1": "SSC Neapel",
  "a2": "Dynamo Dresden",
  "a3": "FC Bayern Munchen",
  "a4": "Juventus Turin",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "Der VfB Stuttgart wurde funf Mal Deutscher Meister. Wann gewannen sie diesen Titel zum ersten Mal?",

  "a1": "1950",
  "a2": "1961",
  "a3": "1952",
  "a4": "1966",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "Wie hei?t das Maskottchen des VfB Stuttgart?",

  "a1": "Fritzle (Krokodil)",
  "a2": "Paule (Pferd)",
  "a3": "Helmut (Lowe)",
  "a4": "Karl (Kanguru)",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "In der Saison 1993/94 trug der VfB ein Ausweichtrikot dessen Hauptfarbe weder mit den Vereins-, Landes- und Stadtfarben ubereinstimmte. Welche Farbe war das?",

  "a1": "Lila",
  "a2": "Grun",
  "a3": "Blau",
  "a4": "Orange",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

{ "question" : {

  "quiz_category": "VfB Stuttgart Quiz",
  "text": "Welcher VfB Spieler schoss in der Meistersaison 2006/07 die meisten Tore?",

  "a1": "Kevin Kuranyi",
  "a2": "Mario Gomez",
  "a3": "Thomas Hitzlsperger",
  "a4": "Sami Khedira",

  "right_answer": "a1",
  "created_at": "02.11.2016"
  "creator": "Miriam Wiedmann"

  }

**Comment by miwiedmann** [comment]
Vorschautexte sind im Wiki
