### ISSUE TITLE
Software

### ISSUE THREAD

**Issue by Zissou90** [th-koeln/wba1-2016-datagram#113]
Yo Company, 

da wir momentan die Über uns Seite erstellen, müssten wir wissen welche Software hier so für das Projekt benutzt habt wäre halt dufte :D wenn  wir es heute hinbekommen könnten

**Comment by janecorleis** [comment]
Atom: http://atom.io

**Comment by marvyyyn** [comment]
Das gabs doch schonmal, sie Issue #38

**Comment by faxemaxe** [comment]
danke marvin!
