### ISSUE TITLE
Lizenzen bitte prüfen

### ISSUE THREAD

**Issue by sbroszio** [th-koeln/wba1-2016-datagram#117]
Ein mal bitte von diesen Bildern
https://commons.wikimedia.org/wiki/File:Cannstatter_Kurve_2013.JPG
https://www.flickr.com/photos/peterfuchs/5722006357
https://www.flickr.com/photos/giesenbauer/3036373628
die Lizenzen prüfen.

Danke ^^

**Comment by skeNe94** [comment]
Sind okay. Können genutzt werden. Es müssen nur jeweils die Autoren mit angegeben werden. Dies machen wir aber dann im Impressum
