### ISSUE TITLE
Frage zum Konzept

### ISSUE THREAD

**Issue by mglugla** [th-koeln/wba1-2016-datagram#118]
Wir haben eine Frage zum Konzept des Quizsliders und würden gegebenenfalls eine Änderung daran vornehmen. An wen können wir uns wenden?

**Comment by marvyyyn** [comment]
Worum geht es denn genau?

Wenns um die Funktionalität geht, bitte an die Gruppe Programmlogik bzw. mich wenden.
Ansonsten mal morgens in großer Runde ansprechen.
