### ISSUE TITLE
fragen.json Fehlerhaft

### ISSUE THREAD

**Issue by radicalm1nd** [th-koeln/wba1-2016-datagram#119]
Die fragen.json kann sowohl von Programmlogik als auch Spiellogik nicht richtig eingebunden werden.
Bitte auf Fehler überprüfen.

**Comment by radicalm1nd** [comment]
ich hab den zum validierern benutzt https://jsonformatter.curiousconcept.com/

**Comment by nassirdreffy** [comment]
Fehler überprüft, gefixed und validiert.  Sollte noch was seien, bitte bescheid geben - danke
