### ISSUE TITLE
Übergabe an Endscreen

### ISSUE THREAD

**Issue by marvyyyn** [th-koeln/wba1-2016-datagram#122]
Für die Übergabe an den Endscreen benötige ich von der Spiellogik folgende Daten:

* quizId
* reachedPoints
* maxPoints
* questions[] (0, 1, 0, 1, 0, 1)  <- Einfach nur 0 falsch, 1 richtig
* timestamp <- Oder Datum und Uhrzeit 

Das ganze muss per Javacript im localStorage gespeichert werden, am besten ein JSON Objekt mittels: `JSON.stringify(array)`

Ein paar Infos dazu gibt es hier: <https://wiki.selfhtml.org/wiki/JavaScript/Web_Storage>

Wenn das Quiz abgeschlossen ist und die Daten gespeichert sind bitte nach: 
`app/endscreen/endscreen.html `weiterleiten.

Danke :)

**Comment by radicalm1nd** [comment]
Hi, hab das zur Kenntnis genommen. Wird als nächstes gecheckt, sobald unser quiz mit der .json funktioniert!
