### ISSUE TITLE
Programmlogik einbinden und eindeutige IDs

### ISSUE THREAD

**Issue by marvyyyn** [th-koeln/wba1-2016-datagram#123]
@startscreen:

In der quiz_start.html bitte folgenden Code in euren ~~<head>-Bereich einbinden:~~

Update 07-11-2016: Nicht in den `<head>` sondern in den `<footer>` Bereich einbinden, sonst fängt @faxemaxe an zu weinen :)

```
<script src="./../programmlogik/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="./../programmlogik/basic.pl.js" type="text/javascript"></script>
<script src="./../programmlogik/quizdetail.pl.js" type="text/javascript"></script>
```

Desweiteren müssen alle HTML Tags die von der Programmlogik geändert bzw. genutzt werden eine eindeutige ID besitzen.

Dazu zählen Überschriften, Bilder, die Buttons, Quizbeschreibungen, Aufrufe, Autor, Erstellt am ...

Das sieht dann z.B. so aus:

```
<div class="AuthorInfo ff--noto-sans fett">
     <time id="createdTime">16.06.2016</time>
     <p id="createdBy">Hennes48</p>
</div>
```

Danke 👍

**Comment by IrgendsonKerl** [comment]
wird bis mittwoch abend gemacht
