### ISSUE TITLE
Die Icons sind zu groß

### ISSUE THREAD

**Issue by AntonHorst** [th-koeln/wba1-2016-datagram#125]
Hallo,
könntet ihr bitte die Icons(arrow-down.png und Magnifying_glass_icon) etwas runter skalieren denn die sind zu groß. Die Icons müssen ja nur ganz klein wenn ihr euch die Mokups anschaut.

Danke

**Comment by faxemaxe** [comment]
Würde sage 128x128px sollte völlig ausreichend sein, das gilt für alle Icons.

**Comment by sbroszio** [comment]
Die größe ließe sich doch auch beim einfügen anpassen, oder?

**Comment by AntonHorst** [comment]
Ja die lassen sich auch so anpassen aber das Problem hierbei ist, dass die Bilder immer in voller größe von der Seite geladen werden und so längere Ladezeiten enstehen wenn die Bilder zu groß sind.

**Comment by sbroszio** [comment]
Ich habe due Icons (als Arrow-down_resized.png & resized_Lupe.png) mit der max. höhe/breite 128px hinzugefügt
