### ISSUE TITLE
Weißer Hintergrund in der Highscoreliste

### ISSUE THREAD

**Issue by marvyyyn** [th-koeln/wba1-2016-datagram#126]
Hallöchen,

ich habe noch einen Fehler in der Highscore gefunden, hinter der Tabelle fehlt ein weißer Hintergrund.
Das führt dazu, das bei wenigen Tabelleneinträgen folgendes Bild entsteht:
https://th-koeln.sciebo.de/index.php/s/YtvVsXetNkGU0lV

**Comment by AntonHorst** [comment]
Kann ich mir deinen code mergen damit ich es sofort mit der funktionierenden Suchfunktion testen kann?

**Comment by marvyyyn** [comment]
Jein. Du kannst das mergen, allerdings wird die Suche nicht funktionieren, weil die Datenstruktur lokal auf deinem Rechner nicht geladen werden kann. 

Ich habe gerade mal nach geschaut, es reicht aus wenn du dem Wrapper ein `height:100%; `verpasst.

Also dem hier:

```
------> <div class="wrapper bg-color--white pl--20"> <--------
	<div class="grid--5-5">
		<table class="" id="table2_hscore">...</table>
		</div>
	</div>
</div>
```

**Comment by AntonHorst** [comment]
Alles klar 
Danke :)
