### ISSUE TITLE
Bitte den Twist eintragen

### ISSUE THREAD

**Issue by Zissou90** [th-koeln/wba1-2016-datagram#128]
[Titel sagt schon alles, danke fürs bearbeiten :)!](https://github.com/th-koeln/wba1-2016-datagram/wiki/0000-%E2%98%86-Fehlerhafte-Dokumentation-%E2%98%86)

**Comment by marvyyyn** [comment]
@Highscore: Ihr fehlt noch.

**Comment by AntonHorst** [comment]
Ist eingetragen.
