### ISSUE TITLE
Spiellogik - Quiz funktioniert nicht mit IDs>1 (suche leute mit JS/Jquery Ahnung :D)

### ISSUE THREAD

**Issue by radicalm1nd** [th-koeln/wba1-2016-datagram#137]
Live Beispiel: http://radicalm1nd.de/projects/quiz/index.html?id=1
http://radicalm1nd.de/projects/quiz/index.html?id=2

mit id=1 funktioniert alles super. Das Quiz holt sich die ersten 10 Fragen mit der ID 1 aus der json, zeigt diese an und hört danach auf. Sobald ich aber die ID ändere, wird allerdings garnichts ausgegeben und die Fragen sind undefined.
Ich denke es liegt entweder daran, dass die methode die sich den Parameter holt nicht richtig funktioniert (da sie als default 1 setzt), oder der Abgleich irgendwie falsch läuft.

Code hier: https://github.com/th-koeln/wba1-2016-datagram/blob/spiellogik/app/spiellogik/controller.js
Zeilen 1-47

**Comment by radicalm1nd** [comment]
Hab das ganze auch mit einem while(ID=ID) loop versucht, aber dadurch crasht dann die ganze Seite @_@

**Comment by marvyyyn** [comment]
Bugfix ist in deinem Branch, einfach pullen.

**Comment by radicalm1nd** [comment]
Super, vielen dank!!
