### ISSUE TITLE
Falsche Frage/Antwort Zuordnung

### ISSUE THREAD

**Issue by radicalm1nd** [th-koeln/wba1-2016-datagram#142]
Klitzekleiner Fehler in der .json, ist wahrscheinlich kaum wichtig aber ich dachte ich schreibe es trotzdem mal rein:

In dem FC Bayern Quiz (ID 2) ist die erste Frage
"Wie hoch ist der Marktwert des aktuellen FC Bayern Kaders Stand Saison 16/17?"
Die Antworten sind Achtel- bis Finale. Das ist glaube ich nicht ganz richtig 😋

**Comment by vdemizki** [comment]
Danke für die Info. Wird geändert. :)
