### ISSUE TITLE
middleman template aufsetzen

### ISSUE THREAD

**Issue by koos** [th-koeln/wba1-2016-datagram#143]
@faxemaxe soll ich? dann lass uns mal darüber skypen wie genau, dann baue ich das.

**Comment by faxemaxe** [comment]
sorry für die späte Antwort, geben dazu im Laufe des Nachmittags Feedback!

**Comment by faxemaxe** [comment]
Ist noch nicht final entschieden, tendieren eigentlich zu einer static html Lösung, haben aber gehört, dass andere Gruppe auch SPAs gemacht haben...gerne skypen wir ein mal kurz, auch mit Marvin.
