### ISSUE TITLE
[INFO] Überschriften Boxen

### ISSUE THREAD

**Issue by AnleAnja** [th-koeln/wba1-2016-datagram#150]
Die kleinen grauen Überschrifts-Boxen bekommen ein p--10 (fs--paragraphs) und die gelben Überschrifts-Boxen bekommen ein p--20 (fs--h1).

(s. [Toolbox Anleitung](https://github.com/th-koeln/wba1-2016-datagram/wiki/06-CSS-Toolbox-Anleitung))

**Comment by Robbsen92** [comment]
Danke!
