### ISSUE TITLE
Lupe und Pfeil nach unten verkleinern

### ISSUE THREAD

**Issue by kimlarastr** [th-koeln/wba1-2016-datagram#151]
Hallo liebe Assets, 
ich hätte nochmal die Bitte an euch, dass ihr mit dem Pfeil nach unten das Selbe machen könntet wie mit der Lupe?  Also einen weißen Border drum rum legen, bzw das Bild verkleinern. Der Pfeil sollte so verkleinert werden, dass er das gleiche Verhältnis hat wie die Lupe. 
Danke euch!

**Comment by sbroszio** [comment]
Ist als "arrow-down_200x200.png" im branch
