### ISSUE TITLE
Dienstags Hangout

### ISSUE THREAD

**Issue by Zissou90** [th-koeln/wba1-2016-datagram#152]
Hey ich bräuchte nochmal von allen 5 Teams die Emailaddys  die an der Unterhaltung mit Jan am Dienstag teilnehmen werden 

Danke

**Comment by radicalm1nd** [comment]
dustin.herzog@googlemail.com

Kannst du deine auch nochmal posten für die Folien? :)

**Comment by marvyyyn** [comment]
marvin.langbein@eventmates.eu

**Comment by AnleAnja** [comment]
*6 Teams. :D 
anja.bertels@hotmail.com

**Comment by faxemaxe** [comment]
maxhoeffner@aol.com

**Comment by Infamous2k9** [comment]
funtik420@googlemail.com (André Funk || HTML CSS Zusammenführung)

**Comment by nassirdreffy** [comment]
nassir-amakran@live.de

**Comment by radicalm1nd** [comment]
Hat jemand Burak's E-Mail für mich? ^^" Hab sie irgendwie verlegt

**Comment by miwiedmann** [comment]
miwese@googlemail.com (Miriam Wiedmann, Social Media stuff)

**Comment by Zissou90** [comment]
Burak6190@googlemail.com
