### ISSUE TITLE
Fertige Präsentation 

### ISSUE THREAD

**Issue by Zissou90** [th-koeln/wba1-2016-datagram#154]
https://drive.google.com/open?id=0B6n9C5e_SJwBdXJoNkN6T0VBVUU

benötige nur noch die Sachen von der Gruppe Spiellogik  und es wäre Prima wenn mir jemand xD erklären könnte wo das" fertige Projekt ist " damit ich es bei " link" eintragen kann :D

**Comment by radicalm1nd** [comment]
Ich habe dir meine Sachen gestern gemailt. (Spiellogik). Hast du nix bekommen? D:

**Comment by Zissou90** [comment]
Also wirklich hab nichts bekommen, hab mich auch gewundert wieso ich 5 Themen hatte aber Spiellogik nicht dabei war, gott sei Dank ist mir das aufgefalen müsste jetzt drin sein ! 

https://drive.google.com/open?id=0B6n9C5e_SJwBdXJoNkN6T0VBVUU (update)

**Comment by radicalm1nd** [comment]
Gut und ja kA. Frage mich auch wo und wie wir uns heute treffen 😆

**Comment by radicalm1nd** [comment]
@marvyyyn so weit wusste ich auch Bescheid. Aber werden wir dann einfach invited oder was?

**Comment by marvyyyn** [comment]
Ja.

**Comment by marvyyyn** [comment]
Gibt es schon irgendwo die aktuelle?

**Comment by Zissou90** [comment]
ja 2.0 xD
