### ISSUE TITLE
Korrektes MarkUp fehlt

### ISSUE THREAD

**Issue by faxemaxe** [th-koeln/wba1-2016-datagram#155]
Hey Team-Quizrunde,

bei der Zusammenführung ist aufgefallen, dass in eurem aktuellen Commit kein MarkUp liegt, welches sich richtig begutachten lässt, wäre ja schade wenn ihr anhand dessen bewertet werden würdet.

Habe mitbekommen, dass da mit der Zusammenführung von Dustin einiges flöten gegangen ist. **Ich schlage vor** ihr holt euch die Files aus einem älteren Commit wieder. Wenn ihr dazu fragen habt, gerne hier oder Donnerstag in der Uni auf mich zukommen.

**Comment by lwirtz1** [comment]
Eigentlich sollte in der Spiellogik der richtige Code mit unserem Code und dem der Spiellogik sein, um die Quizseite einzubinden.

**Comment by lwirtz1** [comment]
Uns wurde nach dem Durcheinander mit der Spiellogik und dem fehlenden Code dann gesagt, wir sollen einfach eine static.html machen, damit man sieht was wir gemacht haben und was Dustin gemacht hat.

**Comment by faxemaxe** [comment]
Ich hab gerade noch mal nur euren Branch gepullt, dann hat das static.html funktioniert, entweder ich hab gestern Nacht um 3 was vercheckt. ;)

Sorry, wenn ich für Verwirrung gesorgt habe.
