### ISSUE TITLE
Fertige Präsentation 2.0

### ISSUE THREAD

**Issue by Zissou90** [th-koeln/wba1-2016-datagram#156]
Habe jetzt alles eingefügt was ich bekommen habe, jedoch fehlen :

Spielogik und Datenstruktur  ich gebe euch sagen wir bis 10 Uhr Zeit mir die Sachen zu schicken, damit ich schnells möglich das eintragen kann.

Die anderen sollen nochmal drüber schauen und mir sagen ob was fehlt oder ka irgendwas falsch dargestellt wird, ich bin heute 24 std erreichbar.

https://github.com/th-koeln/wba1-2016-datagram/tree/Dokumentation_und_Projektmanagement/app/Praesi

**Comment by marvyyyn** [comment]
Feedback:
* Hinter den Bildern ist eine graue Backgroundcolor, sieht man auf der erste Seite beim transparenten Datagrammlogo ganz gut. Ist das gewollt?
* Dieser MI Banner "viel drin" auf der ersten Seite ist redundant.
* Das ist doch auch eine Präsentation über Fubuizz, richtig? Ich finde das kommt nicht rüber, wir haben noch nichtmal das Fubuizzlogo eingebunden. Was will der "Kunde" denn mit unserem Datagrammlogo?
* In diesem Sinne auch mal überlegen: Fubuizz / Datagramm Farben einheitlich verwenden
* Titel der Präsentation, also was oben im Browserfenster ist: Anpassen, bzw. nicht "Praesi". Ist eine Kleinigkeit, aber .. ;-)
* Code Syntax Darstellung ist super schwer lesbar, da gibt es definitiv auch dunkle Styles für.
* Kannst du bitte bei Programmlogik auf der ersten Folie, aus den einzelnen Punkten auch eine Bulletlist machen? (Hab ich verpennt) Dann ist das einheitlich.
* Auf der 4ten Folie von Socialmedia ist ein fehler: `metameta` gibt es nicht.
* Hatten wir nicht besprochen, den weißen Rand um die Bilder zu entfernen?
* Kein Einheitliches Design: Ihr seid doch dafür verantwortlich das das alles identisch aussieht, aktuell sehen alle Gruppen anders aus. Ein gutes Beispiel ist meiner Meinung nach HTML CSS Zusammenführung, das sieht schickt aus, warum übertragen wir das nicht auf die anderen Folien?
* Rechtschreibung mal kontrollieren (z.B. Programmlogik mit einem m im Inhaltsverzeichnis)
* Was macht die ENDE Folie da? Reicht es nicht wenn PM am Ende einfach einen vernünftigen Schlusssatz sagt? Dann merkt man das Ende ist.

**Comment by AnleAnja** [comment]
zur Rechtschreibung:

ich würde im Inhaltsverzeichnis auch "Sozial Media" zu "Social Media" umändern.

**Comment by Zissou90** [comment]
@marvyyyn 
1- Ja wenn man den Border weg macht kommt halt xD dieser schatten
2. Gut ist entfernt~
3. Stimmt, total vergessen xD ersetze das Datagram logo mit dem Fubuizz logo
4. Done
5. Done
*6. musste genauer sein wo meinst du das? Also ich kann alles perfekt lesen* 
7. Es ist doch einheitlich? xD
8. Done
9. Gutes auge , ich hab die anderen Bilder vergessen.. 
10. Wegen dem Einheitlichen, sind wa eigentlich nicht zuständig, wir haben halt nicht abgesprochen wie es " aussehen sollte" eigentlich war es die aufgabe der Leute die uns das schicken aber kann deinem Wunsch nach kommen.
11. Done
12. Geändert , eigentlich dann wollten wir das schlusswort halten, hast jedoch recht.

@AnleAnja 
Mit erleidgt 

ich hätte eher eine Frage ... kann man bei VAR ARBEITSPAKET = "PROGRAMMLOGIK" , bei folie 3 das bild komplett sehen? Ich seh das nur abgehackt kann aber auch dran liegen das ich ein Surface habe.

**Comment by marvyyyn** [comment]
Falls der Schatten weg soll (ich weiß nicht was besser aussieht):
```
.reveal section img {
    background: none;
    box-shadow: none;
}
```

Mit Einheitlich meine ich, das z.B. Zusammenführung vom Style und den Aufzählungen komplett anders aussieht und das man mal überlegen könnte die Fubuizzfarben (schwarz, grau, gelb, rot, evtl. grün) mehr zu nutzen.  Ist aber auch nur ein Vorschlag.

Das abgehackte ist gewollt, drück mal a, w, d dann müsste das durch das Bild scrollen.

**Comment by AnleAnja** [comment]
Ich finde die Code Syntax Darstellung auch schwer lesbar (weil darauf nicht mehr eingegangen wurde), vor allem wenn das Highlighting gelb ist. Weißer Hintergrund ist da ungeeignet, man kann den aber auch irgendwie dunkel machen.

**Comment by marvyyyn** [comment]
Danke, hab ich vergessen. Also so sieht das bei mir aus:
https://th-koeln.sciebo.de/index.php/s/zIrVAQ3llFq4i9s

Und das ist schwer lesbar.

**Comment by Zissou90** [comment]
bin dabei :) !

**Comment by Zissou90** [comment]
Also ich hab mir das nochmal angeschaut wegen der Einheitlich, dafür müsste ich ja praktisch gesehen nur die "Grundgerüst" Seite ändern da sie ja die Wörter jedesmal zugeflogen bekommt und die "überschrift" von Programlogik .

Ich hab trozdem folgendes problem xD ich krieg das nicht hin mit der Code Syntax kann mir da jemand behilflich sein? :D wäre mucho grande

**Comment by faxemaxe** [comment]
Also die Überschriften würde ich so lassen, das war ja so ziemlich das einzige was Jan gut fand. 

Wo kommt denn das Reveal-Design überhaupt her, also das generelle, nicht nur das Highlighting?

**Comment by Zissou90** [comment]
Also so genau weiß ich es auch nicht bzw ich suche es gerade immer noch.. habe es halt versucht mit einem <style> pre die farbe zu ändern aber irgendwo ist halt noch der Code drin der die Farben die ich durch den Style wähle zu ignoieren

**Comment by Zissou90** [comment]
ich lade mal gerade das hoch was ich habe... hab ja etwas an den farben gemacht

**Comment by marvyyyn** [comment]
Das ist ja jetzt nur bunt.

Mein Vorschlag, wäre irgendwie sowas: https://th-koeln.sciebo.de/index.php/s/FEuw8miNEB1xHTm
Wenn du den nutzen willst: https://th-koeln.sciebo.de/index.php/s/fsk9F0AQ2lHrSbV

Ich geh jetzt ins Bett.

**Comment by Zissou90** [comment]
jetzt hab ich verstanden wie du es meinst ja sieht Top aus.

**Comment by Zissou90** [comment]
> jetzt hab ich verstanden wie du es meinst ja sieht Top aus.
>gn8 , ich versuch mal weiter Code Syntax noch zu verbessern xD

So hab das Problem einfach und simple gelöst, den hintergund Schwarzgefärbt, nach geschaut ob man es lesen kann , ich denke **ja**

Was jetzt fehlt ist die verbesserte Version von Spiellogik und Datenstruktur nur hinweis an Datenstruktur das **Video** lässt alles "crashen"

**Comment by nassirdreffy** [comment]
Also brauchst du anstatt das Video was anderes ?

**Comment by nassirdreffy** [comment]
Weil ansonsten habe ich dir ja alles soweit geschickt

**Comment by nassirdreffy** [comment]
![prasi](https://cloud.githubusercontent.com/assets/15031471/20591949/734b8bc2-b22b-11e6-8910-e4f7a9595d49.png)


Komisch, bei mir im Rowser tut er das aber hochladen

**Comment by nassirdreffy** [comment]
![prasi](https://cloud.githubusercontent.com/assets/15031471/20591983/a011138e-b22b-11e6-961e-711cdc313279.png)

**Comment by nassirdreffy** [comment]
bei geht das mit dem iframe und dem video : /. 

@Zissou90  Hab jetzt nur 3 Bilder hinzugefügt und jut is
 https://drive.google.com/open?id=0B1CHCsEWFS3GTXpQclgxWTBGdHc

**Comment by marvyyyn** [comment]
bei Programmlogik: Aus jeweilen bitte mal jeweiligen machen.

**Comment by miwiedmann** [comment]
Ich hab bei der Twitter Card nen Tag vergessen. Da müsste <meta name="twitter:url" content="http://datagram.netlify.com"> noch rein.

**Comment by Zissou90** [comment]
Nassir könntest du 3 und 5 nicht als Bilder sondern als  "<code>" darstellen? Jan meinte gestern das wir keine bilder machen sollen 

anderen sachen habe ich verbessert lade die version nach dem comment hoch.

**Comment by Zissou90** [comment]
Ich mach es schon für dich ganz schnell

**Comment by miwiedmann** [comment]
@zissou90 passt

**Comment by nassirdreffy** [comment]
@Zissou90 dank dir und  sry stand die ganze zeit im Stau amk. Bin jetzt auf jeden Fall da
