### ISSUE TITLE
Code-review für die Klausur?

### ISSUE THREAD

**Issue by ChantalKo** [th-koeln/wba1-2016-datagram#157]
Hey Leute,
von einer anderen Company habe ich gehört, dass sie  sich nochmal treffen und ein Code-Review machen.
Da unser Code ja auch Teil der Klausur wird und es ja eine Menge Code ist, fände ich es super wenn wir das auch machen könnten.  Vielleicht einmal durch die wichtigsten Aufgaben des Projekts im Code gehen oder ähnliches.
Was sagt ihr dazu?

**Comment by faxemaxe** [comment]
Ist vielleicht keine schlechte Idee.

**Comment by Zissou90** [comment]
Zeit und Ort und ich bin dabei

Am 28.11.2016 10:53 schrieb "Max Höffner" <notifications@github.com>:

**Comment by janecorleis** [comment]
Finde die Idee auch gut. 
Eher kurz vor der Prüfung oder demnächst schon?

**Comment by ChantalKo** [comment]
würde sagen vor der Prüfung, also im Januar. Dann müssten sich noch Leute melden die das erklären könnten. Und was genau kommt eigentlich in der Klausur dran von unserem code, weil ich kann doch nicht den kompletten code auswendig kennen oder?

**Comment by janecorleis** [comment]
WBA schreiben wir ja am 30.01., wenn ich mir das richtig notiert habe - wollen wir uns die Woche davor am Freitag (27.01.) treffen? Dann haben wir noch das Wochenende über Zeit, unser Wissen zu festigen, die Termine liegen aber auch nah genug beieinander, sodass einem in der Klausur noch das Eine oder das Andere so einfallen könnte. 
Würde euch das passen?

**Comment by janecorleis** [comment]
Das hat sich nach dem heutigen Tag wohl erledigt, also schließe ich das hier mal
