### ISSUE TITLE
Editor auswählen

### ISSUE THREAD

**Issue by juliell** [th-koeln/wba1-2016-datagram#16]
Der Herr Noss hat mal eine Mail herumgeschickt und da gab es 2 verschiedene Editoren angeboten.
Man sollte sich am Besten auf einen einigen, da manche bestimmt auch andere benutzen.

**Comment by Gast0ne** [comment]
Würde ich den CEO mit einbinden, reden gleich mal mit ihmˆˆ

**Comment by Gast0ne** [comment]
Okay es wurde brackets wurde vom CEO so gesagt.
