### ISSUE TITLE
Ansprechpartner

### ISSUE THREAD

**Issue by Gast0ne** [th-koeln/wba1-2016-datagram#18]
Wir bräuchten aus jeder Gruppe den Ansprechpartner.

Einfach hier drunter kommentieren mit Gruppe und Name (richtig&Git) bitte.

**Comment by janecorleis** [comment]
Startscreen - Jane Corleis, janecorleis

**Comment by Robbsen92** [comment]
Endscreen - Robin Baljan, Robbsen92

**Comment by astrutz** [comment]
Programmlogik - Alex Strutz, astrutz

**Comment by juliell** [comment]
Assetaufbereitung & Management - Julia Voell, juliell

**Comment by miwiedmann** [comment]
Deployment & Marketing - Miriam Wiedmann, miwiedmann

**Comment by skeNe94** [comment]
Rechte - Dennis Horn, skeNe94

**Comment by cnowagk** [comment]
Quizrunde - Christian Nowagk, cnowagk

**Comment by Zissou90** [comment]
Zusammenführung, Quizübersicht, Grundgerüst, Spiellogik, Datenstruktur und Programmablauf, Highscoreliste  
 
Bitte noch einen Ansprechpartner nennen

**Comment by faxemaxe** [comment]
HTML/CSS Zusammenführung – Max Höffner, faxemaxe

**Comment by AnleAnja** [comment]
Grundgerüst - Anja Bertels, AnleAnja

**Comment by AntonHorst** [comment]
Highscoreliste:Anton,antonhorst

**Comment by nassirdreffy** [comment]
Datenstruktur & Programmablauf << nassir amakran

**Comment by radicalm1nd** [comment]
Spiellogik - Dustin Herzog @radicalm1nd

**Comment by Elenaviola** [comment]
Quizübersicht - Elena Correll, Elenaviola

**Comment by Zissou90** [comment]
so haben nun alle
