### ISSUE TITLE
Programmlogik definieren / Abgrenzung zur Spiellogik

### ISSUE THREAD

**Issue by marvyyyn** [th-koeln/wba1-2016-datagram#20]
Programmlogik im Bezog auf die App definieren.
Was ist unsere Aufgabe?

Abgrenzung zur Spiellogik finden.

**Comment by Gast0ne** [comment]
Das könnt ihr auch im Projects in den Tagesplan schieben :-) dann haben wir es auf einen Blick.

**Comment by marvyyyn** [comment]
## Spiellogik:
Alles was in der Quizrunde passiert, plus zusätzlich alles was daraus resultiert (Quizergebnis, Punktestand, richtige/falsche Fragen) etc. 

## Programmlogik: 
Input/Outputmanagement, zur Verfügung stellen von Ladefunktionen für json files, Grundlegende Funktionen außerhalb des Quizzes ( Highscore laden etc),
Eventuell SinglepageApplication?
