### ISSUE TITLE
Absprache

### ISSUE THREAD

**Issue by lwirtz1** [th-koeln/wba1-2016-datagram#22]
Sitzen hinten

**Comment by radicalm1nd** [comment]
Quizrunde macht die "Hülle" des Quizzes, Spiellogik die Funktionen.
Zwischenergebnis: Timer macht Spiellogik
Button Effekte, z.B. rote/grüne Buttons bei falscher/richtiger Antwort macht Spiellogik.

Rest (bis jetzt) Quizrunde
