### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by sbroszio** [th-koeln/wba1-2016-datagram#25]
Wie sieht es mit den Texten aus die z.B zu jedem Fußball Verein verfasst werden sollen?
Ist das Zuständigkeitsbereich einer existierenden Gruppe, oder müssen dafür noch Leute abgestellt werden?
Die Fragen wären da ja auch ein Thema.
Ein Quiz bringt ja ohne Fragen nichts.

**Comment by Sendura** [comment]
Miriam unterstützt (Deployment & Marketing)
