### ISSUE TITLE
Icon Such-/Auswahleiste

### ISSUE THREAD

**Issue by kimlarastr** [th-koeln/wba1-2016-datagram#35]
Wie bekommen wir den Drop-Down Pfeil und das Suchen-Icon (Lupe) hin?

**Comment by kimlarastr** [comment]
Wir haben uns überlegt es über ein ein Texteingabefeld + ein Icon zu gestalten.

**Comment by kimlarastr** [comment]
Eventuell sollten wir noch die Assets Gruppe mit einbeziehen, falls wir wirklich so Icon "Bild" brauchen.

**Comment by faxemaxe** [comment]
Sprecht mich morgen gerne an, wenn ihr Ansätze braucht.
