### ISSUE TITLE
Drop-Down Highscoreliste Zeitraum

### ISSUE THREAD

**Issue by kimlarastr** [th-koeln/wba1-2016-datagram#37]
Was soll hier genau dargestellt werden? (Kalender (von-bis) oder Jahr, Monate etc.)

**Comment by kimlarastr** [comment]
Wir müssen uns mit den Jungs die das Konzept erstellt haben in Verbindung setzten und abklären welche Inhalte hier genau gemeint sind und ob diese evtl. abgeändert werden dürfen.

-> Verbesserungsvorschlag: Den Zeitraum durch die Auswahl eines bestimmten Quizz ersetzen (macht mehr Sinn unserer Meinung nach)

**Comment by kimlarastr** [comment]
Ich habe versucht die Jungs zu kontaktieren, allerdings gibt es in GitHub keine Message Funktion und in einem Issue konnte ich sie auch nicht verklinken. Eine Idee wäre, morgen in den Raum zu gehen und persönlich zu fragen.

**Comment by faxemaxe** [comment]
Ich glaube da sollten wir uns an den ehemaligen vorgaben aus GDVK orientieren, haben die Jungs sicher nicht anders gemacht: [MindMap Vorgaeb](https://www.mindmeister.com/de/529788700?t=XqWiCsImWQ)

Unter dem Punkt **0. Highscoreliste** sind die unterschiedlichen Werte zu finden:

* Tag
* Woche
* Monat
* ewige Rangliste

**Comment by kimlarastr** [comment]
Danke dir! Diese Übersicht kannte ich noch nicht, aber sehr gut zu wissen, dass es sie gibt.
