### ISSUE TITLE
Es gibt jetzt ein Git-CheatSheet im Wiki

### ISSUE THREAD

**Issue by faxemaxe** [th-koeln/wba1-2016-datagram#43]
Da wir ja doch ein paar Befehle für das git-CLI besprochen haben, habe ich die wichtigen noch ein mal auf der Wikiseite [Git CheatSheet](https://github.com/th-koeln/wba1-2016-datagram/wiki/05-Git-CheatSheet) für alle zusammengefasst. Auch mit einem Mini-FAQ. Wenn etwas fehlt schreibt vielleicht einfach hier ein Comment und ich gucke dann mal wie es eingebaut wird, ist vielleicht besser als wenn jeder an dieser Wikiseite rumbastelt.

Max

**Comment by Zissou90** [comment]
hab den Link geändert (a ich es kurz Umbenannt hatte), da der Git CheatSheet irgendwo unten untergegangen ist,

trozdem super Arbeit

**Comment by faxemaxe** [comment]
Danke!
Hatte ich auch kurz drüber nachgedacht, wollte aber dann nicht einfach euer System anpacken.
