### ISSUE TITLE
Bilder Links für die Impressum Seite

### ISSUE THREAD

**Issue by skeNe94** [th-koeln/wba1-2016-datagram#44]
Ich bitte alle die Bilder nutzen, mir die Links zu dem Bild zu zuschicken.

**Comment by jimEka** [comment]
Hi,
[Relevant](https://github.com/th-koeln/wba1-2016-datagram/issues/61)

**Comment by janecorleis** [comment]
War schon auf eurer Wiki-Seite verlinkt:
https://www.pexels.com/photo/stadium-flag-holding-cheering-58461/

**Comment by Robbsen92** [comment]
Hier der Endscreen,
folgende Bilder haben wir verwendet:

https://www.pexels.com/photo/sport-game-match-brasil-41257/
