### ISSUE TITLE
Genauer über Lizenzen informieren und aufschreiben

### ISSUE THREAD

**Issue by skeNe94** [th-koeln/wba1-2016-datagram#45]
Über alle benötigten Lizenzen informieren.
Software-, Bilder-, Musik-, Video-Lizenzen.

**Comment by Zissou90** [comment]
Falls ihr euch Informiert habt, wäre es nett es nochmal schrifftlich niederzuschreiben, wo ihr das herhabt usw , erleichtert dann uns die Arbeit ^^
