### ISSUE TITLE
Timer - Function hinzufügen, wenn timer 0 erreicht

### ISSUE THREAD

**Issue by radicalm1nd** [th-koeln/wba1-2016-datagram#56]
Nachdem der Timer 0 erreicht, muss eine Funktion ausgeführt werden. Dieses muss noch gecodet werden.

Außerdem: Was passiert?

**Comment by Gast0ne** [comment]
Möglichkeit 1: Quiz beendet
Möglichkeit 2: nächste Frage
Möglichkeit 3: anfrage ob man noch anwesend ist
Mal so von mir als Gedanken rein geworfen... :)

Soll es auch einen "nächste Frage" Button geben?
