### ISSUE TITLE
Impressum HTML-Seite erstellen 

### ISSUE THREAD

**Issue by skeNe94** [th-koeln/wba1-2016-datagram#58]
Impressum Seite erstellen.

**Comment by faxemaxe** [comment]
Falls noch nicht ergoogelt [eRecht24 Was ist ein Impressum](https://www.e-recht24.de/artikel/datenschutz/209.html) Dort gibt es sogar einen Impressumsgenerator, den vielleicht nur als Inspiration nutzen. ;)
