### ISSUE TITLE
Quizfragen

### ISSUE THREAD

**Issue by vdemizki** [th-koeln/wba1-2016-datagram#59]
Können wir die Beispielfragen und dazugehörigen Antworten haben?

**Comment by Gast0ne** [comment]
4 Quizes a 10 Fragen

**Comment by miwiedmann** [comment]
Alle Quizfragen sind [hier](https://github.com/th-koeln/wba1-2016-datagram/wiki/Content,-Quizfragen-und-Vorschautexte) zu finden.
