### ISSUE TITLE
Benötigte Medien

### ISSUE THREAD

**Issue by sbroszio** [th-koeln/wba1-2016-datagram#61]
Da die im GDVK verwendeten Bilder urheberrechtlich geschützt sind, haben wir uns entschieden neue lizensfreie Bilder herauszusuchen, die zu den bereits entworfenen Quizspielen passen. 
Wenn ihr also Medien braucht wendet euch bitte **rechtzeitig** an uns. Dazu brauchen wir, vorallem bei Bildern, die ungefähre Größe(Skalierung) dieser.

**Comment by nassirdreffy** [comment]
Hallo,
Wir benötigen die Bilder für die Vereinsquize:

Werder bremen, Bayern München, BVB, Stuttgart VFB.

#Arigato
