### ISSUE TITLE
QUIZ STARTSEITE - Wer macht sie?

### ISSUE THREAD

**Issue by radicalm1nd** [th-koeln/wba1-2016-datagram#62]
Problem: Wir haben anscheinend keine Gruppe, der die **Quiz Startseite** in HTML/CSS erstellt

Quiz Startseite ist die Seite wenn ein Quiz in der Übersicht angeklickt wird und das Quiz dann nocheinmal anteased, bevor die Quizrunde losgeht.

Lösung: Wir müssen wen finden, der das macht 😛

**Comment by Zissou90** [comment]
Das Problem kann man sehr einfach lösen. Die Gruppe [Quizübersicht](https://github.com/th-koeln/wba1-2016-datagram/wiki/04-Company-Zuordnung#4-quiz%C3%BCbersicht)  könnte es coden. Die müssten praktisch eine HTML/CSS erstellen und könnten dabei den Grundgerüst nutzen.

Stellt den Auftrag bei Quizübersicht.

**Comment by IrgendsonKerl** [comment]
Habe das schon erledigt

**Comment by Sendura** [comment]
Wenn es erledigt ist, dann bitte das Issue schließen!
