### ISSUE TITLE
Lizenzen der Bilderquellen

### ISSUE THREAD

**Issue by jimEka** [th-koeln/wba1-2016-datagram#69]
Hi,
wir haben, [in unserem Wiki zugänglich,](https://github.com/th-koeln/wba1-2016-datagram/wiki/Assetsaufbereitung--und-Management) bereits mehrere Bilder rausgesucht, die sich für die Verwendung anbieten. Alle sind von der Platform "Flickr", mit dem Filter "Commercial use & mods allowed". Wir bitten euch, die eizuhaltenden Lizenz-Konditionen, die der hochladenden User jeweils fordert, zu analysieren. Am besten schreibt ihr uns eure Ergebnisse für das jeweilige Bild hier in den Kommentarbereich. Danke!

**Comment by FirdevsK** [comment]
Hi,
man darf alle Bilder verwenden unter der Bedingung, die Quellen mitanzugeben, auch bei Veränderungen und sonstigem Eingreifen des Bildmaterials.

**Comment by sbroszio** [comment]
Danke
