### ISSUE TITLE
Tagesziel Programmlogik

### ISSUE THREAD

**Issue by astrutz** [th-koeln/wba1-2016-datagram#8]
Definition Programmlogik, Abgrenzung zu Spiellogik und Datenstrukturen
Groben Zeitplan entwerfen, Arbeitspakete definieren

Wiki füllen mit:
- Zu erledigende Arbeitspakete
- grober Zeitplan

**Comment by marvyyyn** [comment]
Zwei Arbeitspackete unter Issue #20 und #21 angelegt.
