### ISSUE TITLE
 Visualisierung 

### ISSUE THREAD

**Issue by Sofiesaxo** [th-koeln/wba1-2016-datagram#80]
Es wird eine grobe Visualisierung mit Hilfe eines Mindmaps erstellt.
Danach wird überlegt ob eine detailreiche Übersicht/Dokumentation angefertigt wird oder andere Lösungen eher geeignet sind.

**Comment by Sofiesaxo** [comment]
Visualisierung fertig. Feedback bitte

**Comment by marvyyyn** [comment]
wo?
