### ISSUE TITLE
Javascript Highscore

### ISSUE THREAD

**Issue by astrutz** [th-koeln/wba1-2016-datagram#82]
Script für den Highscore mit
- Zugriff aus der Datenstruktur
- Sortieren
- Suchen
- Filtern
- Verlinkungen

**Comment by marvyyyn** [comment]
~~Zugriff aus der Datenstruktur~~
~~Sortieren~~
~~Suchen~~
~~Filtern~~

Noch offen: Verlinkungen

**Comment by marvyyyn** [comment]
Update 05-11-2016:
*Highscoreliste angepasst an die neue JSON Datenstruktur
*Position werden auch bei Filterung durch Username richtig angezeigt
*Fallunterscheidung: Globale Highscoreliste zu allen Quizzes (alle Punkte werden zusammengerechnet), oder Übergabe einer QuizId
*Position (Index) des Quiz Eintrags in der JSON Datei ermittelbar Warum? Das Quiz mit der ID 1 koennte in der Theorie ganz unten in der Datei stehen, und damit gilt JSON Index != QuizID
*Button Verlinkungen vorbereitet
*Wenn ein User mehrfach gespielt hat, wird nur noch das bessere Ergebnis angezeigt.

**Comment by marvyyyn** [comment]
Update 07-11-2016:
* Verlinkungen/ Buttons sind implementiert

**Comment by marvyyyn** [comment]
Schließe das Issue. Highscoreliste ist fertig.
