### ISSUE TITLE
Javascript Startscreen/Quizdetail Ansicht

### ISSUE THREAD

**Issue by astrutz** [th-koeln/wba1-2016-datagram#85]
Script für den Startscreen
* Zugriff auf die Datenstruktur
* Übergebene QuizId herausfinden
* Daten zum Quiz anzeigen 
* Verlinkungen bzw. Übergabe der QuizID an Spiellogik

**Comment by marvyyyn** [comment]
Issue für die Endscreengruppe angelegt. #123 
Benötigen eindeutige IDs und unser Code muss eingebunden werden.

**Comment by Sofiesaxo** [comment]
Quizdetail Ansicht soweit fertig. -Benötige eindeutige IDs zum fertigstellen.

**Comment by marvyyyn** [comment]
Endscreen ist fertig
