### ISSUE TITLE
Javascript Quizübersicht

### ISSUE THREAD

**Issue by astrutz** [th-koeln/wba1-2016-datagram#86]
Script für die Quizübersicht
- Zugriff auf die Datenstruktur
- Sortieren
- Suchen
- Slider
- Aufklappen der Quizzes
- Verlinkung

**Comment by marvyyyn** [comment]
von Alex erledigt:
* JSON Datei von Datenstruktur wird erfolgreich geladen
* Sortiermöglichkeit über `<select>` Input implementiert
* Suchfunktion implementiert

todo:
* Suchfunktion: Was passiert wenn kein Quiz gefunden wird?
* Suchfunktion: Anzeigebug beheben
* Auf Quizuebersicht Gruppe warten, und Programmlogik in den letztendlichen View implementieren
* Aufklappen der Quizzes in der Übersicht
* Slider

**Comment by astrutz** [comment]
von Alex erledigt:

* JSON Datei von Datenstruktur wird erfolgreich geladen
* Sortiermöglichkeit über <select> Input implementiert
* Suchfunktion implementiert
* Suchfunktion: Was passiert wenn kein Quiz gefunden wird?
* Suchfunktion: Anzeigebug beheben
* Aufklappen der Quizzes in der Übersicht

todo:
* Auf Quizuebersicht Gruppe warten, und Programmlogik in den letztendlichen View implementieren
* Slider

**Comment by marvyyyn** [comment]
Quizübersicht

Einbindung der Quizzes ins "neue" Design
Sortieren und Suchen neu aufrufen
Absprache mit der View.Gruppe, dass nichts mehr geändert wird
Bilder aus JSON laden
