### ISSUE TITLE
Javascript Endscreen

### ISSUE THREAD

**Issue by astrutz** [th-koeln/wba1-2016-datagram#87]
Script für den Endscreen
- Zugriff auf die Datenstruktur
- Daten von Endscreen empfangen
- Quizdaten anzeigen
- Highscore je nach Ergebnis berechnen
- Verlinkungen

**Comment by marvyyyn** [comment]
Issue für die Endscreengruppe angelegt. #121 
Benötigen eindeutige IDs und unser Code muss eingebunden werden.

**Comment by marvyyyn** [comment]
Update:
* JSON Daten werden geladen
* Übergebene Daten werden aus dem localStorage geladen, siehe #122 
* Die Highscoretabelle wird jetzt abhängig von dem Ergebnis berechnet. Es wird immer nur ein Auschnitt angezeigt und der User befindet sich in der Mitte (falls möglich).

toDo:
* Auf Endscreen Gruppe warten, das die HTML Datei angepasst wird #121 
* Slider 
* Verlinkungen

**Comment by marvyyyn** [comment]
Endscreen ist fertig
