### ISSUE TITLE
Auswahl und Input Feld Javascript 

### ISSUE THREAD

**Issue by kimlarastr** [th-koeln/wba1-2016-datagram#99]
Wir müssen uns überlegen, wie wir die Felder lebendig machen. D.h. Javascript (oder JQuery o.ä., je nachdem was man dafür nutzen muss) anwenden damit sich bei der Zeitraum-Auswahl die Tabelle verkleinert und bei der Spiele Suche die Tabelle zum Spieler springt und diesen grau hinterlegt ( wie in der Vorlage). Optimal wäre es auch wenn man bereits eingegebene Spielernamen (evtl in Cookies?) speichern könnte. Das habe ich am 27.10. mit dem CEO Jan Kus bei der Retrospektive so abgesprochen.

**Comment by astrutz** [comment]
Ist das nicht eine Sache der Programmlogik?

**Comment by marvyyyn** [comment]
Hier besteht Redebedarf: Das ist aus unsere Sicht die Aufgabe der Programmlogik und wurde auch schon so bereits fertig programmiert.

**Comment by kimlarastr** [comment]
okay dann hat sich das ja für uns erledigt. Allerdings wurde mit Jan Kos abgesprochen dass es so funktionieren soll wie oben beschrieben =)
